add tt08 hdl projects

diff --git a/.github/workflows/reharden.yaml b/.github/workflows/reharden.yaml
--- a/.github/workflows/reharden.yaml
+++ b/.github/workflows/reharden.yaml
@@ -5,6 +5,216 @@ on:
   workflow_dispatch:
 
 jobs:
+  reharden-tt08:
+    strategy:
+      fail-fast: false
+      matrix:
+        project:
+          - tt_um_16_mic_beamformer_arghunter
+          - tt_um_a1k0n_demo
+          - tt_um_a1k0n_vgadonut
+          - tt_um_benpayne_ps2_decoder
+          - tt_um_betz_morse_keyer
+          - tt_um_brailliance
+          - tt_um_brandonramos_VGA_Pong_with_NES_Controllers
+          - tt_um_bytex64_munch
+          - tt_um_cattuto_sr_latch
+          - tt_um_cejmu
+          - tt_um_cfib_demo
+          - tt_um_clock_divider_arghunter
+          - tt_um_comm_ic_bhavuk
+          - tt_um_crispy_vga
+          - tt_um_daosvik_aesinvsbox
+          - tt_um_ddc_arghunter
+          - tt_um_demosiine_sda
+          - tt_um_dendraws_donut
+          - tt_um_dlfloatmac
+          - tt_um_dlmiles_poc_fskmodem_hdlctrx
+          - tt_um_dlmiles_tt08_poc_uart
+          - tt_um_dmtd_arghunter
+          - tt_um_dpmu
+          - tt_um_dpmunit
+          - tt_um_edwintorok
+          - tt_um_Electom_cla_4bits
+          - tt_um_emilian_muxpga
+          - tt_um_emmyxu_obstacle_detection
+          - tt_um_ephrenm_tsal
+          - tt_um_ezchips_calc
+          - tt_um_faramire_rotary_ring_wrapper
+          - tt_um_faramire_stopwatch
+          - tt_um_favoritohjs_scroller
+          - tt_um_find_the_damn_issue
+          - tt_um_fountaincoder_top_ad
+          - tt_um_gfg_development_tinymandelbrot
+          - tt_um_hack_cpu
+          - tt_um_htfab_bouncy_capsule
+          - tt_um_i2c_peripheral_stevej
+          - tt_um_i2s_to_pwm_arghunter
+          - tt_um_JAC_EE_segdecode
+          - tt_um_jayjaywong12
+          - tt_um_jmack2201
+          - tt_um_johshoff_metaballs
+          - tt_um_kapilan_alarm
+          - tt_um_kb2ghz_xalu
+          - tt_um_LnL_SoC
+          - tt_um_mac
+          - tt_um_mattvenn_rgb_mixer
+          - tt_um_meriac_play_tune
+          - tt_um_MichaelBell_canon
+          - tt_um_MichaelBell_mandelbrot
+          - tt_um_neural_navigators
+          - tt_um_NicklausThompson_SkyKing
+          - tt_um_nvious_graphics
+          - tt_um_nyan
+          - tt_um_patater_demokit
+          - tt_um_pdm_correlator_arghunter
+          - tt_um_pdm_pitch_filter_arghunter
+          - tt_um_pyamnihc_dummy_counter
+          - tt_um_quarren42_demoscene_top
+          - tt_um_ran_DanielZhu
+          - tt_um_resfuzzy
+          - tt_um_Richard28277
+          - tt_um_ring_divider
+          - tt_um_roy1707018
+          - tt_um_samuelm_pwm_generator
+          - tt_um_shuangyu_top
+          - tt_um_sign_addsub
+          - tt_um_silice
+          - tt_um_simon_cipher
+          - tt_um_stochastic_addmultiply_CL123abc
+          - tt_um_supermic_arghunter
+          - tt_um_thexeno_rgbw_controller
+          - tt_um_tmkong_rgb_mixer
+          - tt_um_toivoh_demo_deluxe
+          - tt_um_tommythorn_maxbw
+          - tt_um_top
+          - tt_um_tt08_wirecube
+          - tt_um_vga_cbtest
+          - tt_um_vga_glyph_mode
+          - tt_um_whynot
+          - tt_um_wokwi_407306064811090945
+          - tt_um_yuri_panchul_adder_with_flow_control
+          - tt_um_yuri_panchul_schoolriscv_cpu_with_fibonacci_program
+          - tt_um_yuri_panchul_sea_battle_vga_game
+          - tt_um_zec_square1
+          - tt_um_zoom_zoom
+
+    runs-on: ubuntu-24.04
+    env:
+      OPENLANE_IMAGE_OVERRIDE: htms/openlane2:ihp-v3.0.0.dev17
+      PDK_ROOT: ${{ github.workspace }}/pdk
+      PDK: ihp-sg13g2
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Checkout tt-support-tools repo
+        uses: actions/checkout@v4
+        with:
+          repository: TinyTapeout/tt-support-tools
+          path: tt08-hdl/${{ matrix.project }}/tt
+          ref: ttihp25a
+
+      - name: Checkout IHP PDK repo
+        uses: actions/checkout@v4
+        with:
+          repository: TinyTapeout/IHP-Open-PDK
+          ref: tt2025
+          path: pdk
+
+      - name: Setup python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+
+      - name: Install dependencies
+        working-directory: tt08-hdl/${{ matrix.project }}
+        run: |
+          pip install -r tt/requirements.txt
+
+      - name: Install ghdl
+        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
+        with:
+          packages: ghdl-llvm
+          version: ttihp25a-reharden
+
+      - name: Install OpenLane (IHP branch)
+        shell: bash
+        run: |
+          pip install https://github.com/TinyTapeout/libparse-python/releases/download/0.3.1-dev1/libparse-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
+          pip install https://github.com/TinyTapeout/openlane2/releases/download/ihp-v3.0.0.dev17/openlane-3.0.0.dev17-py3-none-any.whl
+
+      - name: Fetch verilog and build config
+        working-directory: tt08-hdl/${{ matrix.project }}
+        shell: bash
+        run: ./tt/tt_tool.py --create-user-config --ihp
+
+      - name: Make GDS with OpenLane
+        working-directory: tt08-hdl/${{ matrix.project }}
+        run: |
+          git init
+          # tt_tool requires a remote to be set, and some commit to be present
+          git remote add origin https://github.com/TinyTapeout/dummy
+          git config user.email "bot@github.com"
+          git config user.name "Tiny Tapeout Bot"
+          git commit --allow-empty -m "Dummy commit"
+
+          python tt/tt_tool.py --create-user-config --harden --ihp
+
+          # Fail if the final GDS file doesn't exist
+          if [ ! -f "runs/wokwi/final/gds/${{ matrix.project }}.gds" ]; then
+            exit 1
+          fi
+
+          # Fail is error.log isn't empty
+          if [ -s "runs/wokwi/error.log" ]; then
+            exit 1
+          fi
+
+      #- name: Publish build logs
+      #  #if: success() || failure()
+      #  uses: actions/upload-artifact@v4
+      #  with:
+      #    name: GDS_${{ matrix.project }}
+      #    path: |
+      #      tt08-hdl/${{ matrix.project }}/runs/*
+
+      - name: Install KLayout
+        shell: bash
+        run: |
+          wget https://github.com/TinyTapeout/klayout/releases/download/v0.29.11/klayout_0.29.11-1_amd64.deb
+          sudo apt-get update && sudo apt-get install -y ./klayout_0.29.11-1_amd64.deb
+          pip install klayout==0.29.11
+
+      - name: Prepare tt_submission artifact
+        working-directory: tt08-hdl/${{ matrix.project }}
+        shell: bash
+        run: |
+          mkdir -p tt_submission/stats
+          TOP_MODULE=$(./tt/tt_tool.py --print-top-module --ihp)
+          cp runs/wokwi/final/commit_id.json tt_submission/
+          cp runs/wokwi/final/{gds,lef,spef/*}/${TOP_MODULE}.* tt_submission/
+          strm2oas tt_submission/${TOP_MODULE}.gds tt_submission/${TOP_MODULE}.oas
+          if [ "$PDK" == "sky130A" ]; then
+            cp runs/wokwi/final/pnl/${TOP_MODULE}.pnl.v tt_submission/${TOP_MODULE}.v
+          else
+            cp runs/wokwi/final/nl/${TOP_MODULE}.nl.v tt_submission/${TOP_MODULE}.v
+          fi
+          cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,resolved.json} tt_submission/
+          cp runs/wokwi/final/metrics.csv tt_submission/stats/metrics.csv
+          cp runs/wokwi/*-yosys-synthesis/reports/stat.rpt tt_submission/stats/synthesis-stats.txt
+
+      - name: Publish tt_submission artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: tt_submission_${{ matrix.project }}
+          path: |
+            tt08-hdl/${{ matrix.project }}/src/*
+            tt08-hdl/${{ matrix.project }}/docs/*
+            tt08-hdl/${{ matrix.project }}/tt_submission/*
+            tt08-hdl/${{ matrix.project }}/info.yaml
+            tt08-hdl/${{ matrix.project }}/LICENSE
+
   reharden-tt09:
     strategy:
       fail-fast: false
